services:
  xdm:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    network_mode: host
    environment:
      - XDM_DEBUG_MODE=1
    volumes:
      - xdm-app-data:/root/.xdm-app-data
      - ${DOWNLOAD_DIR}:/root/Downloads
    restart: unless-stopped

volumes:
  xdm-app-data:
